services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - ./backend:/app
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    command: go tool air # ホットリロードを実現するためにairを選択.
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    command: pnpm dev --host # --hostはhostマシーンからも接続するための設定.
    ports:
      - "5173:5173"

volumes:
  node_modules:
  go-mod-cache:
  go-build-cache: