name: Frontend CI

on:
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./frontend

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-frontend
      - run: pnpm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-frontend
      - run: pnpm run lint

  steiger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-frontend
      - run: pnpm run steiger
